#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --account=env540
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=05:00:00

# Load modules
module load gcc python

# Activate virtual environment or conda environment
source ~/venvs/ipeo_venv/bin/activate

python cross_val_unet.py --model UNet --resume_lr 1e-5 --resume_ce_weight 0.7 --resume_dice_weight 0.3
